/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AlertRoot: typeof import('./src/components/ui/molecules/AlertRoot.vue')['default']
    BaseButton: typeof import('./src/components/ui/atoms/BaseButton.vue')['default']
    BaseInput: typeof import('./src/components/ui/atoms/BaseInput.vue')['default']
    BaseSpinner: typeof import('./src/components/ui/atoms/BaseSpinner.vue')['default']
    CardRoot: typeof import('./src/components/ui/organisms/CardRoot.vue')['default']
    DialogRoot: typeof import('./src/components/ui/organisms/DialogRoot.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
