/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseInput: typeof import('./src/components/ui/base/BaseInput.vue')['default']
    ButtonWrapper: typeof import('./src/components/ui/global/ButtonWrapper.vue')['default']
    CardWrapper: typeof import('./src/components/ui/global/CardWrapper.vue')['default']
    ModalWrapper: typeof import('./src/components/ui/global/ModalWrapper.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
